// ==========================================================================
// 🔤 BASE DE DATOS DE VOCABULARIO UNIFICADA CON SUPABASE STORAGE (1,000 PALABRAS)
// ==========================================================================

const SUPABASE_BASE_URL = "https://ylhjsbeliblhzkquxjss.supabase.co/storage/v1/object/public/vocabulary-pics";

// Tupla: [id, word, spanish, category, level, syntax, article, hasImage]
const RAW_VOCABULARIO = [
    // --- Tema 1: Expresiones Útiles & Interacción Social Básica ---
    [1, "Please", "Por favor", "expressions", "A1", "expression", null, false],
    [2, "Thank you", "Gracias", "expressions", "A1", "expression", null, false],
    [3, "You're welcome", "De nada", "expressions", "A1", "expression", null, false],
    [4, "Excuse me", "Disculpe", "expressions", "A1", "expression", null, false],
    [5, "I'm sorry", "Lo siento", "expressions", "A1", "expression", null, false],
    [6, "Hello", "Hola", "expressions", "A1", "expression", null, false],
    [7, "Goodbye", "Adiós", "expressions", "A1", "expression", null, false],
    [8, "See you later", "Hasta luego", "expressions", "A1", "expression", null, false],
    [9, "Good morning", "Buenos días", "expressions", "A1", "expression", null, false],
    [10, "Good night", "Buenas noches", "expressions", "A1", "expression", null, false],
    [11, "Yes", "Sí", "expressions", "A1", "expression", null, false],
    [12, "No", "No", "expressions", "A1", "expression", null, false],
    [13, "Maybe", "Tal vez", "expressions", "A1", "expression", null, false],
    [14, "Of course", "Por supuesto", "expressions", "A1", "expression", null, false],
    [15, "No problem", "No hay problema", "expressions", "A1", "expression", null, false],
    [16, "Help me", "Ayúdame", "expressions", "A1", "expression", null, false],
    [17, "I don't know", "No lo sé", "expressions", "A1", "expression", null, false],
    [18, "I understand", "Entiendo", "expressions", "A1", "expression", null, false],
    [19, "Repeat please", "Repita por favor", "expressions", "A1", "expression", null, false],
    [20, "How much", "Cuánto cuesta", "expressions", "A1", "expression", null, false],
    [21, "Bless you", "Salud", "expressions", "A1", "expression", null, false],
    [22, "Nice to meet you", "Mucho gusto", "expressions", "A1", "expression", null, false],
    [23, "Have a good day", "Que tengas un buen día", "expressions", "A1", "expression", null, false],
    [24, "Take care", "Cuídate", "expressions", "A1", "expression", null, false],
    [25, "See you tomorrow", "Hasta mañana", "expressions", "A1", "expression", null, false],

    // --- Tema 2: Casa, Habitación y Objetos ---
    [26, "Kitchen", "Cocina", "house", "A1", "noun", "a", true],
    [27, "Bedroom", "Habitación", "house", "A1", "noun", "a", true],
    [28, "Bathroom", "Baño", "house", "A1", "noun", "a", true],
    [29, "Living room", "Sala de estar", "house", "A1", "noun", "a", true],
    [30, "Garden", "Jardín", "house", "A1", "noun", "a", true],
    [31, "Door", "Puerta", "house", "A1", "noun", "a", true],
    [32, "Window", "Ventana", "house", "A1", "noun", "a", true],
    [33, "Floor", "Piso", "house", "A1", "noun", "a", false],
    [34, "Wall", "Pared", "house", "A1", "noun", "a", false],
    [35, "Ceiling", "Techo interior", "house", "A1", "noun", "a", false],
    [36, "Roof", "Tejado", "house", "A1", "noun", "a", true],
    [37, "Garage", "Cochera", "house", "A1", "noun", "a", false],
    [38, "Balcony", "Balcón", "house", "A1", "noun", "a", true],
    [39, "Basement", "Sótano", "house", "A1", "noun", "a", false],
    [40, "Hallway", "Pasillo", "house", "A1", "noun", "a", false],
    [41, "Bed", "Cama", "house", "A1", "noun", "a", true],
    [42, "Table", "Mesa", "house", "A1", "noun", "a", true],
    [43, "Chair", "Silla", "house", "A1", "noun", "a", true],
    [44, "Sofa", "Sofá", "house", "A1", "noun", "a", true],
    [45, "Desk", "Escritorio", "house", "A1", "noun", "a", true],
    [46, "Lamp", "Lámpara", "house", "A1", "noun", "a", true],
    [47, "Mirror", "Espejo", "house", "A1", "noun", "a", true],
    [48, "Closet", "Armario", "house", "A1", "noun", "a", true],
    [49, "Shelf", "Estante", "house", "A1", "noun", "a", true],
    [50, "Carpet", "Alfombra", "house", "A1", "noun", "a", true],
    [51, "Pillow", "Almohada", "house", "A1", "noun", "a", true],
    [52, "Blanket", "Manta", "house", "A1", "noun", "a", false],
    [53, "Towel", "Toalla", "house", "A1", "noun", "a", true],
    [54, "Curtain", "Cortina", "house", "A1", "noun", "a", true],
    [55, "Clock", "Reloj de pared", "house", "A1", "noun", "a", true],
    [56, "Fridge", "Nevera", "house", "A1", "noun", "a", true],
    [57, "Oven", "Horno", "house", "A1", "noun", "an", true],
    [58, "Microwave", "Microondas", "house", "A1", "noun", "a", true],
    [59, "Stove", "Estufa", "house", "A1", "noun", "a", true],
    [60, "Sink", "Fregadero", "house", "A1", "noun", "a", true],
    [61, "Plate", "Plato", "house", "A1", "noun", "a", true],
    [62, "Glass", "Vaso", "house", "A1", "noun", "a", true],
    [63, "Cup", "Taza", "house", "A1", "noun", "a", true],
    [64, "Fork", "Tenedor", "house", "A1", "noun", "a", true],
    [65, "Spoon", "Cuchara", "house", "A1", "noun", "a", true],
    [66, "Knife", "Cuchillo", "house", "A1", "noun", "a", true],
    [67, "Pan", "Sartén", "house", "A1", "noun", "a", true],
    [68, "Pot", "Olla", "house", "A1", "noun", "a", true],
    [69, "Bottle", "Botella", "house", "A1", "noun", "a", true],
    [70, "Can", "Lata", "house", "A1", "noun", "a", true],
    [71, "Soap", "Jabón", "house", "A1", "noun", null, true],
    [72, "Shampoo", "Champú", "house", "A1", "noun", null, true],
    [73, "Toothbrush", "Cepillo de dientes", "house", "A1", "noun", "a", true],
    [74, "Toilet paper", "Papel higiénico", "house", "A1", "noun", null, true],
    [75, "Comb", "Peine", "house", "A1", "noun", "a", true],
    [76, "Fan", "Ventilador", "house", "A1", "noun", "a", true],
    [77, "Heater", "Calefactor", "house", "A1", "noun", "a", false],
    [78, "Broom", "Escoba", "house", "A1", "noun", "a", true],
    [79, "Trash can", "Cubo de basura", "house", "A1", "noun", "a", true],
    [80, "Bucket", "Balde", "house", "A1", "noun", "a", true],
    [81, "Needle", "Aguja", "house", "A1", "noun", "a", true],
    [82, "Thread", "Hilo", "house", "A1", "noun", null, true],
    [83, "Iron", "Plancha", "house", "A1", "noun", "an", true],
    [84, "Pillowcase", "Funda de almohada", "house", "A1", "noun", "a", false],
    [85, "Mattress", "Colchón", "house", "A1", "noun", "a", true],
    [86, "Mug", "Tazón", "house", "A1", "noun", "a", true],
    [87, "Teapot", "Tetera", "house", "A1", "noun", "a", true],
    [88, "Napkin", "Servilleta", "house", "A1", "noun", "a", true],
    [89, "Tray", "Bandeja", "house", "A1", "noun", "a", false],
    [90, "Pitcher", "Jarra", "house", "A1", "noun", "a", true],

    // --- Tema 3: Ropa, Accesorios & Apariencia ---
    [91, "Shirt", "Camisa", "clothing", "A1", "noun", "a", true],
    [92, "T-shirt", "Camiseta", "clothing", "A1", "noun", "a", true],
    [93, "Pants", "Pantalones", "clothing", "A1", "noun", null, true],
    [94, "Shorts", "Pantalones cortos", "clothing", "A1", "noun", null, true],
    [95, "Jeans", "Vaqueros", "clothing", "A1", "noun", null, true],
    [96, "Dress", "Vestido", "clothing", "A1", "noun", "a", true],
    [97, "Skirt", "Falda", "clothing", "A1", "noun", "a", true],
    [98, "Jacket", "Chaqueta", "clothing", "A1", "noun", "a", true],
    [99, "Coat", "Abrigo", "clothing", "A1", "noun", "a", true],
    [100, "Sweater", "Suéter", "clothing", "A1", "noun", "a", true],
    [101, "Socks", "Calcetines", "clothing", "A1", "noun", null, true],
    [102, "Shoes", "Zapatos", "clothing", "A1", "noun", null, true],
    [103, "Boots", "Botas", "clothing", "A1", "noun", null, true],
    [104, "Sneakers", "Tenis", "clothing", "A1", "noun", null, false],
    [105, "Sandals", "Sandalias", "clothing", "A1", "noun", null, true],
    [106, "Belt", "Cinturón", "clothing", "A1", "noun", "a", true],
    [107, "Hat", "Sombrero", "clothing", "A1", "noun", "a", true],
    [108, "Cap", "Gorra", "clothing", "A1", "noun", "a", true],
    [109, "Gloves", "Guantes", "clothing", "A1", "noun", null, true],
    [110, "Scarf", "Bufanda", "clothing", "A1", "noun", "a", true],
    [111, "Ring", "Anillo", "clothing", "A1", "noun", "an", true],
    [112, "Watch", "Reloj de pulsera", "clothing", "A1", "noun", "a", true],
    [113, "Necklace", "Collar", "clothing", "A1", "noun", "a", true],
    [114, "Glasses", "Gafas", "clothing", "A1", "noun", null, true],
    [115, "Sunglasses", "Gafas de sol", "clothing", "A1", "noun", null, true],
    [116, "Zipper", "Cremallera", "clothing", "A1", "noun", "a", true],
    [117, "Button", "Botón", "clothing", "A1", "noun", "a", true],
    [118, "Pocket", "Bolsillo", "clothing", "A1", "noun", "a", false],
    [119, "Size", "Talla", "clothing", "A1", "noun", "a", false],
    [120, "Umbrella", "Paraguas", "clothing", "A1", "noun", "an", true],
    [121, "Tie", "Corbata", "clothing", "A1", "noun", "a", true],
    [122, "Purse", "Bolso", "clothing", "A1", "noun", "a", true],
    [123, "Wallet", "Billetera", "clothing", "A1", "noun", "a", true],
    [124, "Suit", "Traje", "clothing", "A1", "noun", "a", true],
    [125, "Pyjamas", "Pijama", "clothing", "A1", "noun", null, true],
    [126, "Sleeve", "Manga", "clothing", "A1", "noun", "a", false],
    [127, "Collar", "Cuello de camisa", "clothing", "A1", "noun", "a", false],
    [128, "Shoelace", "Cordon de zapato", "clothing", "A1", "noun", "a", false],
    [129, "Cotton", "Algodón", "clothing", "A1", "noun", null, false],
    [130, "Wool", "Lana", "clothing", "A1", "noun", null, false],
    [131, "Vest", "Chaleco", "clothing", "A1", "noun", "a", true],
    [132, "Slipper", "Pantufla", "clothing", "A1", "noun", "a", false],
    [133, "Bathrobe", "Bata de baño", "clothing", "A1", "noun", "a", true],
    [134, "Uniform", "Uniforme", "clothing", "A1", "noun", "a", false],
    [135, "Hanger", "Percha", "clothing", "A1", "noun", "a", true],

    // --- Tema 4: Comida, Bebidas & Restaurante ---
    [136, "Bread", "Pan", "food", "A1", "noun", null, true],
    [137, "Butter", "Mantequilla", "food", "A1", "noun", null, true],
    [138, "Cheese", "Queso", "food", "A1", "noun", null, true],
    [139, "Milk", "Leche", "food", "A1", "noun", null, true],
    [140, "Egg", "Huevo", "food", "A1", "noun", "an", true],
    [141, "Meat", "Carne", "food", "A1", "noun", null, true],
    [142, "Chicken", "Pollo", "food", "A1", "noun", null, true],
    [143, "Beef", "Carne de res", "food", "A1", "noun", null, true],
    [144, "Pork", "Carne de cerdo", "food", "A1", "noun", null, false],
    [145, "Fish", "Pescado", "food", "A1", "noun", null, true],
    [146, "Rice", "Arroz", "food", "A1", "noun", null, true],
    [147, "Pasta", "Pasta", "food", "A1", "noun", null, true],
    [148, "Soup", "Sopa", "food", "A1", "noun", "a", true],
    [149, "Salad", "Ensalada", "food", "A1", "noun", "a", true],
    [150, "Sauce", "Salsa", "food", "A1", "noun", "a", true],
    [151, "Apple", "Manzana", "food", "A1", "noun", "an", true],
    [152, "Banana", "Plátano", "food", "A1", "noun", "a", true],
    [153, "Orange", "Naranja", "food", "A1", "noun", "an", true],
    [154, "Lemon", "Limón", "food", "A1", "noun", "a", true],
    [155, "Grape", "Uva", "food", "A1", "noun", "a", true],
    [156, "Potato", "Patata", "food", "A1", "noun", "a", true],
    [157, "Tomato", "Tomate", "food", "A1", "noun", "a", true],
    [158, "Onion", "Cebolla", "food", "A1", "noun", "an", true],
    [159, "Garlic", "Ajo", "food", "A1", "noun", null, true],
    [160, "Carrot", "Zanahoria", "food", "A1", "noun", "a", true],
    [161, "Lettuce", "Lechuga", "food", "A1", "noun", null, true],
    [162, "Mushroom", "Champiñón", "food", "A1", "noun", "a", true],
    [163, "Pepper", "Pimiento", "food", "A1", "noun", "a", true],
    [164, "Bean", "Frijol", "food", "A1", "noun", "a", true],
    [165, "Corn", "Maíz", "food", "A1", "noun", null, true],
    [166, "Water", "Agua", "food", "A1", "noun", null, true],
    [167, "Coffee", "Café", "food", "A1", "noun", null, true],
    [168, "Tea", "Té", "food", "A1", "noun", null, true],
    [169, "Juice", "Jugo", "food", "A1", "noun", null, true],
    [170, "Soda", "Refresco", "food", "A1", "noun", "a", true],
    [171, "Cake", "Pastel", "food", "A1", "noun", "a", true],
    [172, "Ice cream", "Helado", "food", "A1", "noun", null, true],
    [173, "Chocolate", "Chocolate", "food", "A1", "noun", null, true],
    [174, "Sugar", "Azúcar", "food", "A1", "noun", null, true],
    [175, "Salt", "Sal", "food", "A1", "noun", null, true],
    [176, "Sweet", "Dulce", "food", "A1", "adjective", null, true],
    [177, "Salty", "Salado", "food", "A1", "adjective", null, true],
    [178, "Sour", "Agrio", "food", "A1", "adjective", null, true],
    [179, "Bitter", "Amargo", "food", "A1", "adjective", null, true],
    [180, "Spicy", "Picante", "food", "A1", "adjective", null, true],
    [181, "Breakfast", "Desayuno", "food", "A1", "noun", "a", true],
    [182, "Lunch", "Almuerzo", "food", "A1", "noun", "a", true],
    [183, "Dinner", "Cena", "food", "A1", "noun", "a", true],
    [184, "Snack", "Bocado", "food", "A1", "noun", "a", true],
    [185, "Menu", "Menú", "food", "A1", "noun", "a", true],
    [186, "Steak", "Filete", "food", "A1", "noun", "a", true],
    [187, "Sandwich", "Sándwich", "food", "A1", "noun", "a", true],
    [188, "Pizza", "Pizza", "food", "A1", "noun", "a", true],
    [189, "Ham", "Jamón", "food", "A1", "noun", null, true],
    [190, "Turkey", "Pavo", "food", "A1", "noun", null, true],
    [191, "Seafood", "Mariscos", "food", "A1", "noun", null, true],
    [192, "Shrimp", "Camarón", "food", "A1", "noun", "a", true],
    [193, "Tuna", "Atún", "food", "A1", "noun", null, true],
    [194, "Oil", "Aceite", "food", "A1", "noun", null, true],
    [195, "Vinegar", "Vinagre", "food", "A1", "noun", null, true],
    [196, "Honey", "Miel", "food", "A1", "noun", null, true],
    [197, "Jam", "Mermelada", "food", "A1", "noun", null, true],
    [198, "Apple juice", "Jugo de manzana", "food", "A1", "noun", null, true],
    [199, "Milkshake", "Batido", "food", "A1", "noun", "a", true],
    [200, "Beer", "Cerveza", "food", "A1", "noun", "a", true],
    [201, "Wine", "Vino", "food", "A1", "noun", "a", true],
    [202, "Cocktail", "Cóctel", "food", "A1", "noun", "a", true],
    [203, "Spaghetti", "Espagueti", "food", "A1", "noun", null, true],
    [204, "Noodles", "Fideos", "food", "A1", "noun", null, true],
    [205, "Omelette", "Tortilla de huevo", "food", "A1", "noun", "an", true],
    [206, "Toast", "Tostada", "food", "A1", "noun", "a", true],
    [207, "Cereal", "Cereal", "food", "A1", "noun", null, true],

    // --- Tema 5: Cuerpo, Salud & Aseo ---
    [208, "Head", "Cabeza", "body", "A1", "noun", "a", true],
    [209, "Face", "Cara", "body", "A1", "noun", "a", true],
    [210, "Hair", "Cabello", "body", "A1", "noun", null, true],
    [211, "Eye", "Ojo", "body", "A1", "noun", "an", true],
    [212, "Ear", "Oreja", "body", "A1", "noun", "an", true],
    [213, "Nose", "Nariz", "body", "A1", "noun", "a", true],
    [214, "Mouth", "Boca", "body", "A1", "noun", "a", true],
    [215, "Tooth", "Diente", "body", "A1", "noun", "a", true],
    [216, "Lip", "Labio", "body", "A1", "noun", "a", true],
    [217, "Tongue", "Lengua", "body", "A1", "noun", "a", true],
    [218, "Neck", "Cuello", "body", "A1", "noun", "a", true],
    [219, "Shoulder", "Hombro", "body", "A1", "noun", "a", true],
    [220, "Arm", "Brazo", "body", "A1", "noun", "an", true],
    [221, "Hand", "Mano", "body", "A1", "noun", "a", true],
    [222, "Finger", "Dedo de la mano", "body", "A1", "noun", "a", true],
    [223, "Chest", "Pecho", "body", "A1", "noun", "a", true],
    [224, "Back", "Espalda", "body", "A1", "noun", "a", true],
    [225, "Stomach", "Estómago", "body", "A1", "noun", "a", true],
    [226, "Leg", "Pierna", "body", "A1", "noun", "a", true],
    [227, "Foot", "Pie", "body", "A1", "noun", "a", true],
    [228, "Pain", "Dolor", "body", "A1", "noun", "a", true],
    [229, "Fever", "Fiebre", "body", "A1", "noun", "a", true],
    [230, "Cough", "Tos", "body", "A1", "noun", "a", true],
    [231, "Cold", "Resfriado", "body", "A1", "noun", "a", true],
    [232, "Allergy", "Alergia", "body", "A1", "noun", "an", true],
    [233, "Doctor", "Médico", "body", "A1", "noun", "a", true],
    [234, "Nurse", "Enfermero/a", "body", "A1", "noun", "a", true],
    [235, "Hospital", "Hospital", "body", "A1", "noun", "a", true],
    [236, "Pharmacy", "Farmacia", "body", "A1", "noun", "a", true],
    [237, "Medicine", "Medicina", "body", "A1", "noun", null, true],

    // --- Tema 6: Ciudad, Transporte & Orientación ---
    [238, "Street", "Calle", "city", "A1", "noun", "a", true],
    [239, "Avenue", "Avenida", "city", "A1", "noun", "an", true],
    [240, "Park", "Parque", "city", "A1", "noun", "a", true],
    // --- Tema 7: Tiempo, Fechas & Clima (TI) ---
    [241, "Second", "Segundo", "time", "A1", "noun", "a", true],
    [242, "Minute", "Minuto", "time", "A1", "noun", "a", true],
    [243, "Hour", "Hora", "time", "A1", "noun", "an", true],
    [244, "Day", "Día", "time", "A1", "noun", "a", true],
    [245, "Week", "Semana", "time", "A1", "noun", "a", true],
    [246, "Month", "Mes", "time", "A1", "noun", "a", true],
    [247, "Year", "Año", "time", "A1", "noun", "a", true],
    [248, "Morning", "Mañana", "time", "A1", "noun", "a", true],
    [249, "Afternoon", "Tarde", "time", "A1", "noun", "an", true],
    [250, "Night", "Noche", "time", "A1", "noun", "a", true],
    [251, "Today", "Hoy", "time", "A1", "adverb", null, true],
    [252, "Tomorrow", "Mañana", "time", "A1", "adverb", null, true],
    [253, "Yesterday", "Ayer", "time", "A1", "adverb", null, true],
    [254, "Now", "Ahora", "time", "A1", "adverb", null, true],
    [255, "Later", "Más tarde", "time", "A1", "adverb", null, true],
    [256, "Monday", "Lunes", "time", "A1", "noun", null, true],
    [257, "Tuesday", "Martes", "time", "A1", "noun", null, true],
    [258, "Wednesday", "Miércoles", "time", "A1", "noun", null, true],
    [259, "Thursday", "Jueves", "time", "A1", "noun", null, true],
    [260, "Friday", "Viernes", "time", "A1", "noun", null, true],
    [261, "Saturday", "Sábado", "time", "A1", "noun", null, true],
    [262, "Sunday", "Domingo", "time", "A1", "noun", null, true],
    [263, "Weekend", "Fin de semana", "time", "A1", "noun", "a", true],
    [264, "Always", "Siempre", "time", "A1", "adverb", null, true],
    [265, "Never", "Nunca", "time", "A1", "adverb", null, true],
    [266, "Sun", "Sol", "weather", "A1", "noun", "a", true],
    [267, "Rain", "Lluvia", "weather", "A1", "noun", null, true],
    [268, "Wind", "Viento", "weather", "A1", "noun", null, true],
    [269, "Snow", "Nieve", "weather", "A1", "noun", null, true],
    [270, "Cloud", "Nube", "weather", "A1", "noun", "a", true],
    [271, "Hot", "Caluroso", "weather", "A1", "adjective", null, true],
    [272, "Cold", "Frío", "weather", "A1", "adjective", null, true],
    [273, "Warm", "Cálido", "weather", "A1", "adjective", null, true],
    [274, "Cool", "Fresco", "weather", "A1", "adjective", null, true],
    [275, "Weather", "Clima", "weather", "A1", "noun", null, true],
    [276, "January", "Enero", "time", "A1", "noun", null, true],
    [277, "February", "Febrero", "time", "A1", "noun", null, true],
    [278, "March", "Marzo", "time", "A1", "noun", null, true],
    [279, "April", "Abril", "time", "A1", "noun", null, true],
    [280, "May", "Mayo", "time", "A1", "noun", null, true],
    [281, "June", "Junio", "time", "A1", "noun", null, true],
    [282, "July", "Julio", "time", "A1", "noun", null, true],
    [283, "August", "Agosto", "time", "A1", "noun", null, true],
    [284, "September", "Septiembre", "time", "A1", "noun", null, true],
    [285, "October", "Octubre", "time", "A1", "noun", null, true],
    [286, "November", "Noviembre", "time", "A1", "noun", null, true],
    [287, "December", "Diciembre", "time", "A1", "noun", null, true],
    [288, "Season", "Estación", "time", "A1", "noun", "a", true],
    [289, "Storm", "Tormenta", "weather", "A1", "noun", "a", true],
    [290, "Thunder", "Trueno", "weather", "A1", "noun", null, true],
    [291, "Sunrise", "Amanecer", "time", "A1", "noun", "a", true],
    [292, "Sunset", "Atardecer", "time", "A1", "noun", "a", true],
    [293, "Daylight", "Luz del día", "time", "A1", "noun", null, true],
    [294, "Dusk", "Anochecer", "time", "A1", "noun", null, true],
    [295, "Dawn", "Alba", "time", "A1", "noun", null, true],

    // --- Tema 8: Familia, Personas & Animales (PE) ---
    [296, "Mother", "Madre", "family", "A1", "noun", "a", true],
    [297, "Father", "Padre", "family", "A1", "noun", "a", true],
    [298, "Son", "Hijo", "family", "A1", "noun", "a", true],
    [299, "Daughter", "Hija", "family", "A1", "noun", "a", true],
    [300, "Baby", "Bebé", "family", "A1", "noun", "a", true],
    [301, "Brother", "Hermano", "family", "A1", "noun", "a", true],
    [302, "Sister", "Hermana", "family", "A1", "noun", "a", true],
    [303, "Husband", "Esposo", "family", "A1", "noun", "a", true],
    [304, "Wife", "Esposa", "family", "A1", "noun", "a", true],
    [305, "Friend", "Amigo/a", "family", "A1", "noun", "a", true],
    [306, "Boy", "Niño", "family", "A1", "noun", "a", true],
    [307, "Girl", "Niña", "family", "A1", "noun", "a", true],
    [308, "Man", "Hombre", "family", "A1", "noun", "a", true],
    [309, "Woman", "Mujer", "family", "A1", "noun", "a", true],
    [310, "Child", "Niño/a", "family", "A1", "noun", "a", true],
    [311, "Dog", "Perro", "animals", "A1", "noun", "a", true],
    [312, "Cat", "Gato", "animals", "A1", "noun", "a", true],
    [313, "Bird", "Pájaro", "animals", "A1", "noun", "a", true],
    [314, "Fish", "Pez", "animals", "A1", "noun", "a", true],
    [315, "Horse", "Caballo", "animals", "A1", "noun", "a", true],
    [316, "Cow", "Vaca", "animals", "A1", "noun", "a", true],
    [317, "Pig", "Cerdo", "animals", "A1", "noun", "a", true],
    [318, "Sheep", "Oveja", "animals", "A1", "noun", "a", true],
    [319, "Mouse", "Ratón", "animals", "A1", "noun", "a", true],
    [320, "Lion", "León", "animals", "A1", "noun", "a", true],
    [321, "Uncle", "Tío", "family", "A1", "noun", "an", true],
    [322, "Aunt", "Tía", "family", "A1", "noun", "an", true],
    [323, "Cousin", "Primo/a", "family", "A1", "noun", "a", true],
    [324, "Nephew", "Sobrino", "family", "A1", "noun", "a", true],
    [325, "Niece", "Sobrina", "family", "A1", "noun", "a", true],
    [326, "Grandfather", "Abuelo", "family", "A1", "noun", "a", true],
    [327, "Grandmother", "Abuela", "family", "A1", "noun", "a", true],
    [328, "Grandson", "Nieto", "family", "A1", "noun", "a", true],
    [329, "Granddaughter", "Nieta", "family", "A1", "noun", "a", true],
    [330, "Relative", "Pariente", "family", "A1", "noun", "a", true],
    [331, "Duck", "Pato", "animals", "A1", "noun", "a", true],
    [332, "Chicken", "Pollo", "animals", "A1", "noun", "a", true],
    [333, "Rabbit", "Conejo", "animals", "A1", "noun", "a", true],
    [334, "Bear", "Oso", "animals", "A1", "noun", "a", true],
    [335, "Wolf", "Lobo", "animals", "A1", "noun", "a", true],
    [336, "Elephant", "Elefante", "animals", "A1", "noun", "an", true],
    [337, "Giraffe", "Jirafa", "animals", "A1", "noun", "a", true],
    [338, "Monkey", "Mono", "animals", "A1", "noun", "a", true],
    [339, "Tiger", "Tigre", "animals", "A1", "noun", "a", true],
    [340, "Snake", "Serpiente", "animals", "A1", "noun", "a", true],

    // --- Tema 9: Adjetivos Básicos (AD) ---
    [341, "Big", "Grande", "adjectives", "A1", "adjective", null, true],
    [342, "Small", "Pequeño", "adjectives", "A1", "adjective", null, true],
    [343, "Tall", "Alto", "adjectives", "A1", "adjective", null, true],
    [344, "Short", "Corto / Bajo", "adjectives", "A1", "adjective", null, true],
    [345, "Long", "Largo", "adjectives", "A1", "adjective", null, true],
    [346, "Good", "Bueno", "adjectives", "A1", "adjective", null, true],
    [347, "Bad", "Malo", "adjectives", "A1", "adjective", null, true],
    [348, "Fast", "Rápido", "adjectives", "A1", "adjective", null, true],
    [349, "Slow", "Lento", "adjectives", "A1", "adjective", null, true],
    [350, "Strong", "Fuerte", "adjectives", "A1", "adjective", null, true],
    [351, "Happy", "Feliz", "adjectives", "A1", "adjective", null, true],
    [352, "Sad", "Triste", "adjectives", "A1", "adjective", null, true],
    [353, "Tired", "Cansado", "adjectives", "A1", "adjective", null, true],
    [354, "Angry", "Enojado", "adjectives", "A1", "adjective", null, true],
    [355, "Scared", "Asustado", "adjectives", "A1", "adjective", null, true],
    [356, "Clean", "Limpio", "adjectives", "A1", "adjective", null, true],
    [357, "Dirty", "Sucio", "adjectives", "A1", "adjective", null, true],
    [358, "New", "Nuevo", "adjectives", "A1", "adjective", null, true],
    [359, "Old", "Viejo", "adjectives", "A1", "adjective", null, true],
    [360, "Young", "Joven", "adjectives", "A1", "adjective", null, true],
    [361, "Cheap", "Barato", "adjectives", "A1", "adjective", null, true],
    [362, "Expensive", "Costoso", "adjectives", "A1", "adjective", null, true],
    [363, "Easy", "Fácil", "adjectives", "A1", "adjective", null, true],
    [364, "Hard", "Difícil / Duro", "adjectives", "A1", "adjective", null, true],
    [365, "Open", "Abierto", "adjectives", "A1", "adjective", null, true],
    [366, "Rich", "Rico", "adjectives", "A1", "adjective", null, true],
    [367, "Poor", "Pobre", "adjectives", "A1", "adjective", null, true],
    [368, "Safe", "Seguro", "adjectives", "A1", "adjective", null, true],
    [369, "Dangerous", "Peligroso", "adjectives", "A1", "adjective", null, true],
    [370, "Quiet", "Tranquilo / Silencioso", "adjectives", "A1", "adjective", null, true],
    [371, "Loud", "Ruidoso / Alto", "adjectives", "A1", "adjective", null, true],
    [372, "Bright", "Brillante", "adjectives", "A1", "adjective", null, true],
    [373, "Dark", "Oscuro", "adjectives", "A1", "adjective", null, true],
    [374, "Warm", "Cálido", "adjectives", "A1", "adjective", null, true],
    [375, "Cool", "Fresco", "adjectives", "A1", "adjective", null, true],
    [376, "Full", "Lleno", "adjectives", "A1", "adjective", null, true],
    [377, "Empty", "Vacío", "adjectives", "A1", "adjective", null, true],
    [378, "Heavy", "Pesado", "adjectives", "A1", "adjective", null, true],
    [379, "Light", "Ligero", "adjectives", "A1", "adjective", null, true],
    [380, "Wet", "Mojado", "adjectives", "A1", "adjective", null, true],
    [381, "Soft", "Suave", "adjectives", "A1", "adjective", null, true],
    [382, "Hard", "Duro", "adjectives", "A1", "adjective", null, true],
    [383, "Smooth", "Liso", "adjectives", "A1", "adjective", null, true],
    [384, "Rough", "Áspero", "adjectives", "A1", "adjective", null, true],
    [385, "Sharp", "Afilado", "adjectives", "A1", "adjective", null, true],

    // --- Tema 10: Verbos Cotidianos Básicos (VE) ---
    [386, "Eat", "Comer", "verbs", "A1", "verb", null, true],
    [387, "Drink", "Beber", "verbs", "A1", "verb", null, true],
    [388, "Sleep", "Dormir", "verbs", "A1", "verb", null, true],
    [389, "Wake up", "Despertar", "verbs", "A1", "verb", null, true],
    [390, "Wash", "Lavar", "verbs", "A1", "verb", null, true],
    [391, "Cook", "Cocinar", "verbs", "A1", "verb", null, true],
    [392, "Clean", "Limpiar", "verbs", "A1", "verb", null, true],
    [393, "Open", "Abrir", "verbs", "A1", "verb", null, true],
    [394, "Close", "Cerrar", "verbs", "A1", "verb", null, true],
    [395, "Buy", "Comprar", "verbs", "A1", "verb", null, true],
    [396, "Walk", "Caminar", "verbs", "A1", "verb", null, true],
    [397, "Run", "Correr", "verbs", "A1", "verb", null, true],
    [398, "Drive", "Conducir", "verbs", "A1", "verb", null, true],
    [399, "Travel", "Viajar", "verbs", "A1", "verb", null, true],
    [400, "Go", "Ir", "verbs", "A1", "verb", null, true],
    [401, "Speak", "Hablar", "verbs", "A1", "verb", null, true],
    [402, "Listen", "Escuchar", "verbs", "A1", "verb", null, true],
    [403, "Read", "Leer", "verbs", "A1", "verb", null, true],
    [404, "Write", "Escribir", "verbs", "A1", "verb", null, true],
    [405, "See", "Ver", "verbs", "A1", "verb", null, true],
    [406, "Like", "Gustar", "verbs", "A1", "verb", null, true],
    [407, "Want", "Querer", "verbs", "A1", "verb", null, true],
    [408, "Need", "Necesitar", "verbs", "A1", "verb", null, true],
    [409, "Have", "Tener", "verbs", "A1", "verb", null, true],
    [410, "Work", "Trabajar", "verbs", "A1", "verb", null, true],
    [411, "Sit", "Sentarse", "verbs", "A1", "verb", null, true],
    [412, "Stand", "Estar de pie", "verbs", "A1", "verb", null, true],
    [413, "Wait", "Esperar", "verbs", "A1", "verb", null, true],
    [414, "Stop", "Detenerse", "verbs", "A1", "verb", null, true],
    [415, "Start", "Comenzar", "verbs", "A1", "verb", null, true],
    [416, "Pay", "Pagar", "verbs", "A1", "verb", null, true],
    [417, "Cost", "Costar", "verbs", "A1", "verb", null, true],
    [418, "Sell", "Vender", "verbs", "A1", "verb", null, true],
    [419, "Change", "Cambiar", "verbs", "A1", "verb", null, true],
    [420, "Choose", "Elegir", "verbs", "A1", "verb", null, true],
    [421, "Bring", "Traer", "verbs", "A1", "verb", null, true],
    [422, "Take", "Tomar / Llevar", "verbs", "A1", "verb", null, true],
    [423, "Put", "Poner", "verbs", "A1", "verb", null, true],
    [424, "Give", "Dar", "verbs", "A1", "verb", null, true],
    [425, "Get", "Obtener / Conseguir", "verbs", "A1", "verb", null, true],
    [426, "Find", "Encontrar", "verbs", "A1", "verb", null, true],
    [427, "Lose", "Perder", "verbs", "A1", "verb", null, true],
    [428, "Look", "Mirar", "verbs", "A1", "verb", null, true],
    [429, "Watch", "Observar / Ver", "verbs", "A1", "verb", null, true],
    [430, "Show", "Mostrar", "verbs", "A1", "verb", null, true],
    [431, "Play", "Jugar / Tocar instrumento", "verbs", "A1", "verb", null, true],
    [432, "Listen", "Escuchar", "verbs", "A1", "verb", null, true],
    [433, "Dance", "Bailar", "verbs", "A1", "verb", null, true],
    [434, "Sing", "Cantar", "verbs", "A1", "verb", null, true],
    [435, "Draw", "Dibujar", "verbs", "A1", "verb", null, true],

    // --- PARTE 2: NIVEL AVANZADO (B1 - B2) ---

    // --- Tema 1: Expresiones Avanzadas, Conectores & Muletillas (EX) ---
    [436, "As far as I know", "Hasta donde yo sé", "expressions", "B1", "expression", null, false],
    [437, "In my opinion", "En mi opinión", "expressions", "B1", "expression", null, false],
    [438, "To be honest", "Para ser honesto", "expressions", "B1", "expression", null, false],
    [439, "By the way", "Por cierto", "expressions", "B1", "expression", null, false],
    [440, "On the other hand", "Por otro lado", "expressions", "B1", "expression", null, false],
    [441, "Long story short", "En resumen", "expressions", "B1", "expression", null, false],
    [442, "It depends on", "Depende de", "expressions", "B1", "expression", null, false],
    [443, "Make sure that", "Asegúrate de que", "expressions", "B1", "expression", null, false],
    [444, "I have no idea", "No tengo idea", "expressions", "B1", "expression", null, false],
    [445, "Never mind", "No importa", "expressions", "B1", "expression", null, false],
    [446, "So far so good", "Hasta ahora todo bien", "expressions", "B1", "expression", null, false],
    [447, "I'm looking forward to", "Tengo muchas ganas de", "expressions", "B1", "expression", null, false],
    [448, "It's up to you", "Depende de ti", "expressions", "B1", "expression", null, false],
    [449, "I agree with you", "Estoy de acuerdo contigo", "expressions", "B1", "expression", null, false],
    [450, "I don't mind", "No me importa / No me molesta", "expressions", "B1", "expression", null, false],
    [451, "That makes sense", "Tiene sentido", "expressions", "B1", "expression", null, false],
    [452, "I get it", "Lo entiendo", "expressions", "B1", "expression", null, false],
    [453, "Speaking of which", "Hablando de lo cual", "expressions", "B1", "expression", null, false],
    [454, "At the end of the day", "Al fin y al cabo", "expressions", "B1", "expression", null, false],
    [455, "Out of the blue", "De la nada / Inesperadamente", "expressions", "B1", "expression", null, false],
    [456, "Long time no see", "Cuánto tiempo sin verte", "expressions", "B1", "expression", null, false],
    [457, "I'm on my way", "Estoy en camino", "expressions", "B1", "expression", null, false],
    [458, "Sounds good to me", "Me parece bien", "expressions", "B1", "expression", null, false],
    [459, "It goes without saying", "Sobra decirlo", "expressions", "B1", "expression", null, false],
    [460, "Better late than never", "Más vale tarde que nunca", "expressions", "B1", "expression", null, false],

    // --- Tema 2: Negocios, Trabajo & Entorno Corporativo (BUS) ---
    [461, "Deadline", "Fecha límite", "business", "B1", "noun", "a", true],
    [462, "Schedule", "Horario / Agenda", "business", "B1", "noun", "a", true],
    [463, "Project", "Proyecto", "business", "B1", "noun", "a", true],
    [464, "Task", "Tarea", "business", "B1", "noun", "a", true],
    [465, "Report", "Informe", "business", "B1", "noun", "a", true],
    [466, "Boss", "Jefe", "business", "B1", "noun", "a", true],
    [467, "Employee", "Empleado", "business", "B1", "noun", "an", true],
    [468, "Colleague", "Colega de trabajo", "business", "B1", "noun", "a", true],
    [469, "Client", "Cliente", "business", "B1", "noun", "a", true],
    [470, "Partner", "Socio", "business", "B1", "noun", "a", true],
    [471, "Salary", "Salario", "business", "B1", "noun", "a", true],
    [472, "Contract", "Contrato", "business", "B1", "noun", "a", true],
    [473, "Resume", "Currículum", "business", "B1", "noun", "a", true],
    [474, "Interview", "Entrevista", "business", "B1", "noun", "an", true],
    [475, "Career", "Carrera profesional", "business", "B1", "noun", "a", true],
    [476, "Revenue", "Ingresos", "business", "B1", "noun", null, true],
    [477, "Profit", "Ganancia", "business", "B1", "noun", "a", true],
    [478, "Loss", "Pérdida", "business", "B1", "noun", "a", true],
    [479, "Budget", "Presupuesto", "business", "B1", "noun", "a", true],
    [480, "Investment", "Inversión", "business", "B1", "noun", "an", true],
    [481, "Stakeholder", "Partes interesadas", "business", "B1", "noun", "a", true],
    [482, "Market share", "Cuota de mercado", "business", "B1", "noun", "a", true],
    [483, "Growth", "Crecimiento", "business", "B1", "noun", null, true],
    [484, "Performance", "Rendimiento", "business", "B1", "noun", null, true],
    [485, "Strategy", "Estrategia", "business", "B1", "noun", "a", true],
    [486, "Meeting", "Reunión", "business", "B1", "noun", "a", true],
    [487, "Presentation", "Presentación", "business", "B1", "noun", "a", true],
    [488, "Feedback", "Retroalimentación", "business", "B1", "noun", null, true],
    [489, "Goal", "Meta / Objetivo", "business", "B1", "noun", "a", true],
    [490, "Milestone", "Hito / Logro", "business", "B1", "noun", "a", true],
    [491, "Proposal", "Propuesta", "business", "B1", "noun", "a", true],
    [492, "Agreement", "Acuerdo", "business", "B1", "noun", "an", true],
    [493, "Deal", "Trato", "business", "B1", "noun", "a", true],
    [494, "Clause", "Cláusula", "business", "B1", "noun", "a", true],
    [495, "Compromise", "Compromiso", "business", "B1", "noun", "a", true],
    [496, "Overtime", "Horas extras", "business", "B1", "noun", null, true],
    [497, "Promotion", "Ascenso", "business", "B1", "noun", "a", true],
    [498, "Resignation", "Renuncia", "business", "B1", "noun", "a", true],
    [499, "Layoff", "Despido colectivo", "business", "B1", "noun", "a", true],
    [500, "Workload", "Carga de trabajo", "business", "B1", "noun", "a", true],
    [501, "Supplier", "Proveedor", "business", "B1", "noun", "a", true],
    [502, "Customer service", "Atención al cliente", "business", "B1", "noun", null, true],
    [503, "Quality", "Calidad", "business", "B1", "noun", null, true],
    [504, "Efficiency", "Eficiencia", "business", "B1", "noun", null, true],
    [505, "Productivity", "Productividad", "business", "B1", "noun", null, true],
    [506, "Leadership", "Liderazgo", "business", "B1", "noun", null, true],
    [507, "Management", "Gestión / Administración", "business", "B1", "noun", null, true],
    [508, "Teamwork", "Trabajo en equipo", "business", "B1", "noun", null, true],
    [509, "Innovation", "Innovación", "business", "B1", "noun", null, true],
    [510, "Competition", "Competencia", "business", "B1", "noun", null, true],
    [511, "Outsourcing", "Subcontratación", "business", "B1", "noun", null, true],
    [512, "Benchmark", "Punto de referencia", "business", "B1", "noun", "a", true],
    [513, "Brainstorm", "Lluvia de ideas", "business", "B1", "noun", "a", true],
    [514, "Mindset", "Mentalidad", "business", "B1", "noun", "a", true],
    [515, "Workflow", "Flujo de trabajo", "business", "B1", "noun", "a", true],
    [516, "Core competence", "Competencia clave", "business", "B1", "noun", "a", true],
    [517, "Best practice", "Buena práctica", "business", "B1", "noun", "a", true],
    [518, "Deliverable", "Entregable", "business", "B1", "noun", "a", true],
    [519, "Key performance", "Rendimiento clave", "business", "B1", "noun", null, true],
    [520, "Scalability", "Escalabilidad", "business", "B1", "noun", null, true],
    [521, "Turnover", "Rotación de personal / Facturación", "business", "B1", "noun", null, true],
    [522, "Severance", "Indemnización por despido", "business", "B1", "noun", null, true],
    [523, "Headhunter", "Cazatalentos", "business", "B1", "noun", "a", true],
    [524, "Onboarding", "Incorporación / Integración", "business", "B1", "noun", null, true],
    [525, "Payroll", "Nómina", "business", "B1", "noun", "a", true],
    [526, "Procurement", "Adquisición / Compras", "business", "B1", "noun", null, true],
    [527, "Compliance", "Cumplimiento normativo", "business", "B1", "noun", null, true],
    [528, "Logistics", "Logística", "business", "B1", "noun", null, true],
    [529, "Inventory", "Inventario", "business", "B1", "noun", "an", true],
    [530, "Wholesale", "Venta al por mayor", "business", "B1", "noun", null, true],
    [531, "Headquarters", "Sede central", "business", "B1", "noun", null, true],
    [532, "Subsidiary", "Filial / Subsidaria", "business", "B1", "noun", "a", true],
    [533, "Conglomerate", "Conglomerado", "business", "B1", "noun", "a", true],
    [534, "Joint venture", "Empresa conjunta", "business", "B1", "noun", "a", true],
    [535, "Merger", "Fusión empresarial", "business", "B1", "noun", "a", true],
    // --- Tema 3: Tecnología, Software & Medios Digitales (TEC) ---
    [536, "Password", "Contraseña", "technology", "B1", "noun", "a", true],
    [537, "Account", "Cuenta", "technology", "B1", "noun", "an", true],
    [538, "Connection", "Conexión", "technology", "B1", "noun", "a", true],
    [539, "File", "Archivo", "technology", "B1", "noun", "a", true],
    [540, "Software", "Software / Programa", "technology", "B1", "noun", null, true],
    [541, "Screen", "Pantalla", "technology", "B1", "noun", "a", true],
    [542, "Keyboard", "Teclado", "technology", "B1", "noun", "a", true],
    [543, "Mouse", "Ratón", "technology", "B1", "noun", "a", true],
    [544, "Laptop", "Computadora portátil", "technology", "B1", "noun", "a", true],
    [545, "Charger", "Cargador", "technology", "B1", "noun", "a", true],
    [546, "Network", "Red", "technology", "B1", "noun", "a", true],
    [547, "Server", "Servidor", "technology", "B1", "noun", "a", true],
    [548, "Database", "Base de datos", "technology", "B1", "noun", "a", true],
    [549, "Storage", "Almacenamiento", "technology", "B1", "noun", null, true],
    [550, "Security", "Seguridad", "technology", "B1", "noun", null, true],
    [551, "Download", "Descargar", "technology", "B1", "verb", null, true],
    [552, "Upload", "Subir / Cargar", "technology", "B1", "verb", null, true],
    [553, "Update", "Actualizar", "technology", "B1", "verb", null, true],
    [554, "Delete", "Eliminar / Borrar", "technology", "B1", "verb", null, true],
    [555, "Install", "Instalar", "technology", "B1", "verb", null, true],
    [556, "Bug", "Error de software / Bug", "technology", "B1", "noun", "a", true],
    [557, "Error", "Error", "technology", "B1", "noun", "an", true],
    [558, "Feature", "Característica / Función", "technology", "B1", "noun", "a", true],
    [559, "Application", "Aplicación", "technology", "B1", "noun", "an", true],
    [560, "User", "Usuario", "technology", "B1", "noun", "a", true],
    [561, "Link", "Enlace / Link", "technology", "B1", "noun", "a", true],
    [562, "Website", "Sitio web", "technology", "B1", "noun", "a", true],
    [563, "Browser", "Navegador", "technology", "B1", "noun", "a", true],
    [564, "Search", "Búsqueda", "technology", "B1", "noun", "a", true],
    [565, "Folder", "Carpeta", "technology", "B1", "noun", "a", true],
    [566, "Cloud", "Nube", "technology", "B1", "noun", "a", true],
    [567, "Backup", "Copia de seguridad", "technology", "B1", "noun", "a", true],
    [568, "Privacy", "Privacidad", "technology", "B1", "noun", null, true],
    [569, "Access", "Acceso", "technology", "B1", "noun", null, true],
    [570, "Code", "Código", "technology", "B1", "noun", null, true],
    [571, "Encryption", "Encriptación", "technology", "B2", "noun", null, true],
    [572, "Firewall", "Cortafuegos", "technology", "B2", "noun", "a", true],
    [573, "Bandwidth", "Ancho de banda", "technology", "B2", "noun", null, true],
    [574, "Algorithm", "Algoritmo", "technology", "B2", "noun", "an", true],
    [575, "Framework", "Marco de trabajo / Framework", "technology", "B2", "noun", "a", true],
    [576, "Interface", "Interfaz", "technology", "B2", "noun", "an", true],
    [577, "Repository", "Repositorio", "technology", "B2", "noun", "a", true],
    [578, "Deployment", "Despliegue", "technology", "B2", "noun", null, true],
    [579, "Refactoring", "Refactorización", "technology", "B2", "noun", null, true],
    [580, "Debugging", "Depuración", "technology", "B2", "noun", null, true],
    [581, "Artificial intelligence", "Inteligencia artificial", "technology", "B2", "noun", null, true],
    [582, "Machine learning", "Aprendizaje automático", "technology", "B2", "noun", null, true],
    [583, "Data science", "Ciencia de datos", "technology", "B2", "noun", null, true],
    [584, "Automation", "Automatización", "technology", "B2", "noun", null, true],
    [585, "Endpoint", "Punto final / Endpoint", "technology", "B2", "noun", "an", true],
    [586, "Latency", "Latencia", "technology", "B2", "noun", null, true],
    [587, "Throughput", "Rendimiento de procesamiento", "technology", "B2", "noun", null, true],
    [588, "Protocol", "Protocolo", "technology", "B2", "noun", "a", true],
    [589, "Virtualization", "Virtualización", "technology", "B2", "noun", null, true],
    [590, "Container", "Contenedor", "technology", "B2", "noun", "a", true],
    [591, "Kubernetes", "Kubernetes", "technology", "B2", "noun", null, true],
    [592, "Microservice", "Microservicio", "technology", "B2", "noun", "a", true],
    [593, "Serverless", "Sin servidor / Serverless", "technology", "B2", "adjective", null, true],

    // --- Tema 4: Finanzas, Banca & Comercio (FIN) ---
    [594, "Money", "Dinero", "finance", "B1", "noun", null, true],
    [595, "Cash", "Efectivo", "finance", "B1", "noun", null, true],
    [596, "Credit card", "Tarjeta de crédito", "finance", "B1", "noun", "a", true],
    [597, "Bank", "Banco", "finance", "B1", "noun", "a", true],
    [598, "Invoice", "Factura", "finance", "B1", "noun", "an", true],
    [599, "Receipt", "Recibo", "finance", "B1", "noun", "a", true],
    [600, "Tax", "Impuesto", "finance", "B1", "noun", "a", true],
    [601, "Discount", "Descuento", "finance", "B1", "noun", "a", true],
    [602, "Debt", "Deuda", "finance", "B1", "noun", "a", true],
    [603, "Transfer", "Transferencia", "finance", "B1", "noun", "a", true],
    [604, "Fee", "Tarifa / Comision", "finance", "B1", "noun", "a", true],
    [605, "Balance", "Saldo", "finance", "B1", "noun", "a", true],
    [606, "Loan", "Préstamo", "finance", "B1", "noun", "a", true],
    [607, "Interest", "Interés", "finance", "B1", "noun", null, true],
    [608, "Currency", "Moneda / Divisa", "finance", "B1", "noun", "a", true],
    [609, "Exchange rate", "Tipo de cambio", "finance", "B1", "noun", "an", true],
    [610, "Wealth", "Riqueza", "finance", "B1", "noun", null, true],
    [611, "Asset", "Activo", "finance", "B1", "noun", "an", true],
    [612, "Liability", "Pasivo / Obligación", "finance", "B1", "noun", "a", true],
    [613, "Mortgage", "Hipoteca", "finance", "B1", "noun", "a", true],
    [614, "Insurance", "Seguro", "finance", "B1", "noun", null, true],
    [615, "Expense", "Gasto", "finance", "B1", "noun", "an", true],
    [616, "Saving", "Ahorro", "finance", "B1", "noun", "a", true],
    [617, "Payment", "Pago", "finance", "B1", "noun", "a", true],
    [618, "Dividend", "Dividendo", "finance", "B2", "noun", "a", true],
    [619, "Portfolio", "Portafolio de inversión", "finance", "B2", "noun", "a", true],
    [620, "Equity", "Patrimonio / Acciones", "finance", "B2", "noun", null, true],
    [621, "Capital", "Capital", "finance", "B2", "noun", null, true],
    [622, "Bankruptcy", "Bancarrota", "finance", "B2", "noun", null, true],
    [623, "Hedge", "Cobertura financiera", "finance", "B2", "noun", "a", true],
    [624, "Audit", "Auditoría", "finance", "B2", "noun", "an", true],
    [625, "Valuation", "Valuación", "finance", "B2", "noun", "a", true],
    [626, "Liquidity", "Liquidez", "finance", "B2", "noun", null, true],
    [627, "Insolvency", "Insolvencia", "finance", "B2", "noun", null, true],
    [628, "Deficit", "Déficit", "finance", "B2", "noun", "a", true],
    [629, "Surplus", "Superávit", "finance", "B2", "noun", "a", true],
    [630, "Inflation", "Inflación", "finance", "B2", "noun", null, true],
    [631, "Recession", "Recesión", "finance", "B2", "noun", "a", true],
    [632, "Stagnation", "Estancamiento", "finance", "B2", "noun", null, true],
    [633, "Commodity", "Materia prima", "finance", "B2", "noun", "a", true],
    [634, "Derivative", "Derivado financiero", "finance", "B2", "noun", "a", true],
    [635, "Annuity", "Anualidad", "finance", "B2", "noun", "an", true],
    [636, "Depreciation", "Depreciación", "finance", "B2", "noun", null, true],
    [637, "Amortization", "Amortización", "finance", "B2", "noun", null, true],

    // --- Tema 5: Salud Avanzada, Psicología & Bienestar (ADV-HE) ---
    [638, "Disease", "Enfermedad", "health", "B1", "noun", "a", true],
    [639, "Infection", "Infección", "health", "B1", "noun", "an", true],
    [640, "Symptom", "Síntoma", "health", "B1", "noun", "a", true],
    [641, "Diagnosis", "Diagnóstico", "health", "B1", "noun", "a", true],
    [642, "Treatment", "Tratamiento", "health", "B1", "noun", "a", true],
    [643, "Prescription", "Receta médica", "health", "B1", "noun", "a", true],
    [644, "Dosage", "Dosis", "health", "B1", "noun", "a", true],
    [645, "Side effect", "Efecto secundario", "health", "B1", "noun", "a", true],
    [646, "Vaccine", "Vacuna", "health", "B1", "noun", "a", true],
    [647, "Surgery", "Cirugía", "health", "B1", "noun", "a", true],
    [648, "Stress", "Estrés", "health", "B1", "noun", null, true],
    [649, "Anxiety", "Ansiedad", "health", "B1", "noun", null, true],
    [650, "Mental health", "Salud mental", "health", "B1", "noun", null, true],
    [651, "Therapy", "Terapia", "health", "B1", "noun", "a", true],
    [652, "Recovery", "Recuperación", "health", "B1", "noun", "a", true],
    [653, "Muscle", "Músculo", "health", "B1", "noun", "a", true],
    [654, "Bone", "Hueso", "health", "B1", "noun", "a", true],
    [655, "Joint", "Articulación", "health", "B1", "noun", "a", true],
    [656, "Brain", "Cerebro", "health", "B1", "noun", "a", true],
    [657, "Heart", "Corazón", "health", "B1", "noun", "a", true],
    [658, "Exhaustion", "Agotamiento", "health", "B1", "noun", null, true],
    [659, "Insomnia", "Insomnio", "health", "B1", "noun", null, true],
    [660, "Nutrition", "Nutrición", "health", "B1", "noun", null, true],
    [661, "Fitness", "Acondicionamiento físico", "health", "B1", "noun", null, true],
    [662, "Injury", "Lesión", "health", "B1", "noun", "an", true],
    [663, "Rehabilitation", "Rehabilitación", "health", "B2", "noun", null, true],
    [664, "Chronic", "Crónico", "health", "B2", "adjective", null, true],
    [665, "Acute", "Agudo", "health", "B2", "adjective", null, true],
    [666, "Transplant", "Trasplante", "health", "B2", "noun", "a", true],
    [667, "Quarantine", "Cuarentena", "health", "B2", "noun", "a", true],
    [668, "Burnout", "Agotamiento profesional", "health", "B2", "noun", null, true],
    [669, "Depression", "Depresión", "health", "B2", "noun", null, true],
    [670, "Cognitive", "Cognitivo", "health", "B2", "adjective", null, true],
    [671, "Mindfulness", "Atención plena", "health", "B2", "noun", null, true],
    [672, "Resilience", "Resiliencia", "health", "B2", "noun", null, true],
    [673, "Prognosis", "Pronóstico médico", "health", "B2", "noun", "a", true],
    [674, "Biopsy", "Biopsia", "health", "B2", "noun", "a", true],
    [675, "Anesthesia", "Anestesia", "health", "B2", "noun", null, true],
    [676, "Intensive care", "Cuidados intensivos", "health", "B2", "noun", null, true],
    [677, "Outpatient", "Paciente ambulatorio", "health", "B2", "noun", "an", true],

    // --- Tema 6: Viajes Avanzados, Logística & Trámites (TRA) ---
    [678, "Reservation", "Reserva", "travel", "B1", "noun", "a", true],
    [679, "Luggage", "Equipaje", "travel", "B1", "noun", null, true],
    [680, "Boarding pass", "Pase de abordar", "travel", "B1", "noun", "a", true],
    [681, "Customs", "Aduana", "travel", "B1", "noun", null, true],
    [682, "Delay", "Retraso", "travel", "B1", "noun", "a", true],
    [683, "Flight", "Vuelo", "travel", "B1", "noun", "a", true],
    [684, "Departure", "Salida", "travel", "B1", "noun", "a", true],
    [685, "Arrival", "Llegada", "travel", "B1", "noun", "an", true],
    [686, "Gate", "Puerta de embarque", "travel", "B1", "noun", "a", true],
    [687, "Seat", "Asiento", "travel", "B1", "noun", "a", true],
    [688, "Visa", "Visado", "travel", "B1", "noun", "a", true],
    [689, "Passport", "Pasaporte", "travel", "B1", "noun", "a", true],
    [690, "Identity", "Identidad", "travel", "B1", "noun", "an", true],
    [691, "Border", "Frontera", "travel", "B1", "noun", "a", true],
    [692, "Hotel", "Hotel", "travel", "B1", "noun", "a", true],
    [693, "Booking", "Reserva", "travel", "B1", "noun", "a", true],
    [694, "Check-in", "Registro de entrada", "travel", "B1", "noun", "a", true],
    [695, "Check-out", "Registro de salida", "travel", "B1", "noun", "a", true],
    [696, "Reception", "Recepción", "travel", "B1", "noun", "a", true],
    [697, "Destination", "Destino", "travel", "B1", "noun", "a", true],
    [698, "Route", "Ruta", "travel", "B1", "noun", "a", true],
    [699, "Map", "Mapa", "travel", "B1", "noun", "a", true],
    [700, "Guide", "Guía", "travel", "B1", "noun", "a", true],
    [701, "Passenger", "Pasajero", "travel", "B1", "noun", "a", true],
    [702, "Embassy", "Embajada", "travel", "B2", "noun", "an", true],
    [703, "Consulate", "Consulado", "travel", "B2", "noun", "a", true],
    [704, "Itinerary", "Itinerario", "travel", "B2", "noun", "an", true],
    [705, "Layover", "Escala de vuelo", "travel", "B2", "noun", "a", true],
    [706, "Excursion", "Excursión", "travel", "B2", "noun", "an", true],
    [707, "Vaccination", "Vacunación", "travel", "B2", "noun", "a", true],
    [708, "Declaration", "Declaración aduanera", "travel", "B2", "noun", "a", true],
    [709, "Duty-free", "Libre de impuestos", "travel", "B2", "adjective", null, true],
    [710, "Overbooking", "Sobreventa de pasajes", "travel", "B2", "noun", null, true],
    [711, "Reimbursement", "Reembolso", "travel", "B2", "noun", "a", true],
    [712, "Disembark", "Desembarcar", "travel", "B2", "verb", null, true],
    [713, "Transit", "Tránsito", "travel", "B2", "noun", null, true],
    [714, "Transportation", "Transporte", "travel", "B2", "noun", null, true],
    [715, "Waybill", "Guía de transporte", "travel", "B2", "noun", "a", true],
    [716, "Freight", "Carga / Flete", "travel", "B2", "noun", null, true],

    // --- Tema 7: Modismos Corporativos & Idioms (IDI) [EXPRESIONES SIN IMAGEN] ---
    [717, "Touch base", "Ponerse en contacto", "expressions", "B2", "expression", null, false],
    [718, "Bottleneck", "Cuello de botella", "expressions", "B2", "expression", null, false],
    [719, "Ballpark figure", "Cifra aproximada", "expressions", "B2", "expression", null, false],
    [720, "Win-win", "Ganar-ganar", "expressions", "B2", "expression", null, false],
    [721, "Trade-off", "Compromiso / Intercambio", "expressions", "B2", "expression", null, false],
    [722, "Think outside the box", "Pensar diferente", "expressions", "B2", "expression", null, false],
    [723, "Back to square one", "Volver al punto de partida", "expressions", "B2", "expression", null, false],
    [724, "Call it a day", "Dar por terminado el día", "expressions", "B2", "expression", null, false],
    [725, "Cut corners", "Tomar atajos", "expressions", "B2", "expression", null, false],
    [726, "Hit the nail on the head", "Dar en el clavo", "expressions", "B2", "expression", null, false],
    [727, "On the same page", "Estar en la misma sintonía", "expressions", "B2", "expression", null, false],
    [728, "Play it by ear", "Improvisar sobre la marcha", "expressions", "B2", "expression", null, false],
    [729, "Raise the bar", "Elevar el nivel / Estándar", "expressions", "B2", "expression", null, false],
    [730, "Ahead of the curve", "Adelantado a su época", "expressions", "B2", "expression", null, false],
    [731, "Bite the bullet", "Hacer de tripas corazón", "expressions", "B2", "expression", null, false],
    [732, "Burn the midnight oil", "Trabajar hasta muy tarde", "expressions", "B2", "expression", null, false],
    [733, "Game changer", "Factor decisivo", "expressions", "B2", "expression", null, false],
    [734, "Keep me in the loop", "Manténme informado", "expressions", "B2", "expression", null, false],
    [735, "Break the ice", "Romper el hielo", "expressions", "B2", "expression", null, false],
    [736, "Red tape", "Burocracia", "expressions", "B2", "expression", null, false],
    [737, "Take the lead", "Tomar la iniciativa", "expressions", "B2", "expression", null, false],
    [738, "Get the ball rolling", "Poner en marcha", "expressions", "B2", "expression", null, false],
    [739, "Across the board", "A todos los niveles", "expressions", "B2", "expression", null, false],
    [740, "In the loop", "Al tanto de la situación", "expressions", "B2", "expression", null, false],
    [741, "Shed light on", "Aclarar / Arrojar luz sobre", "expressions", "B2", "expression", null, false],
    [742, "Pave the way", "Allanar el camino", "expressions", "B2", "expression", null, false],
    [743, "Steep learning curve", "Curva de aprendizaje empinada", "expressions", "B2", "expression", null, false],
    [744, "Bottom line", "Conclusión / Resultado final", "expressions", "B2", "expression", null, false],
    [745, "Move the needle", "Hacer una diferencia notable", "expressions", "B2", "expression", null, false],
    [746, "Touch and go", "Incierto / Inestable", "expressions", "B2", "expression", null, false],
    [747, "In a nutshell", "En pocas palabras", "expressions", "B2", "expression", null, false],
    [748, "On the fence", "Indeciso", "expressions", "B2", "expression", null, false],
    [749, "Play devil's advocate", "Hacer de abogado del diablo", "expressions", "B2", "expression", null, false],
    [750, "See eye to eye", "Estar de acuerdo", "expressions", "B2", "expression", null, false],
    [751, "Under the weather", "Indispuesto / Algo enfermo", "expressions", "B2", "expression", null, false],
    [752, "Back to the drawing board", "Reiniciar desde cero", "expressions", "B2", "expression", null, false],
    [753, "Blessing in disguise", "No hay mal que por bien no venga", "expressions", "B2", "expression", null, false],
    [754, "Call a spade a spade", "Llamar a las cosas por su nombre", "expressions", "B2", "expression", null, false],
    [755, "Elephant in the room", "Un problema obvio que se ignora", "expressions", "B2", "expression", null, false],
    [756, "Give the benefit of the doubt", "Dar el beneficio de la duda", "expressions", "B2", "expression", null, false],

    // --- Tema 8: Adjetivos Avanzados & Calificativos (ADV-AD) ---
    [757, "Efficient", "Eficiente", "adjectives", "B1", "adjective", null, true],
    [758, "Reliable", "Confiable", "adjectives", "B1", "adjective", null, true],
    [759, "Strict", "Estricto", "adjectives", "B1", "adjective", null, true],
    [760, "Ambitious", "Ambicioso", "adjectives", "B1", "adjective", null, true],
    [761, "Cautious", "Cauteloso", "adjectives", "B1", "adjective", null, true],
    [762, "Useful", "Útil", "adjectives", "B1", "adjective", null, true],
    [763, "Useless", "Inútil", "adjectives", "B1", "adjective", null, true],
    [764, "Expensive", "Costoso", "adjectives", "B1", "adjective", null, true],
    [765, "Reasonable", "Razonable", "adjectives", "B1", "adjective", null, true],
    [766, "Complex", "Complejo", "adjectives", "B1", "adjective", null, true],
    [767, "Suitable", "Adecuado", "adjectives", "B1", "adjective", null, true],
    [768, "Relevant", "Relevante", "adjectives", "B1", "adjective", null, true],
    [769, "Significant", "Significativo", "adjectives", "B1", "adjective", null, true],
    [770, "Essential", "Esencial", "adjectives", "B1", "adjective", null, true],
    [771, "Optional", "Opcional", "adjectives", "B1", "adjective", null, true],
    [772, "Likely", "Probable", "adjectives", "B1", "adjective", null, true],
    [773, "Unlikely", "Improbable", "adjectives", "B1", "adjective", null, true],
    [774, "Doubtful", "Dudoso", "adjectives", "B1", "adjective", null, true],
    [775, "Definite", "Definitivo", "adjectives", "B1", "adjective", null, true],
    [776, "Temporary", "Temporal", "adjectives", "B1", "adjective", null, true],
    [777, "Permanent", "Permanente", "adjectives", "B1", "adjective", null, true],
    [778, "Accurate", "Preciso", "adjectives", "B1", "adjective", null, true],
    [779, "Flexible", "Flexible", "adjectives", "B1", "adjective", null, true],
    [780, "Crucial", "Crucial", "adjectives", "B1", "adjective", null, true],
    [781, "Obvious", "Obvio", "adjectives", "B1", "adjective", null, true],
    [782, "Inevitable", "Inevitable", "adjectives", "B2", "adjective", null, true],
    [783, "Unprecedented", "Sin precedentes", "adjectives", "B2", "adjective", null, true],
    [784, "Substantial", "Sustancial", "adjectives", "B2", "adjective", null, true],
    [785, "Pragmatic", "Pragmático", "adjectives", "B2", "adjective", null, true],
    [786, "Coherent", "Coherente", "adjectives", "B2", "adjective", null, true],
    [787, "Ambiguous", "Ambiguo", "adjectives", "B2", "adjective", null, true],
    [788, "Meticulous", "Meticuloso", "adjectives", "B2", "adjective", null, true],
    [789, "Versatile", "Versátil", "adjectives", "B2", "adjective", null, true],
    [790, "Resilient", "Resiliente", "adjectives", "B2", "adjective", null, true],
    [791, "Pivotal", "Fundamental / Clave", "adjectives", "B2", "adjective", null, true],
    [792, "Sustainable", "Sostenible", "adjectives", "B2", "adjective", null, true],
    [793, "Comprehensive", "Exhaustivo / Integral", "adjectives", "B2", "adjective", null, true],
    [794, "Feasible", "Factible", "adjectives", "B2", "adjective", null, true],
    [795, "Proactive", "Proactivo", "adjectives", "B2", "adjective", null, true],
    [796, "Redundant", "Redundante", "adjectives", "B2", "adjective", null, true],
    [797, "Paramount", "Primordial / De suma importancia", "adjectives", "B2", "adjective", null, true],
    [798, "Indispensable", "Indispensable", "adjectives", "B2", "adjective", null, true],
    [799, "Formidable", "Formidable", "adjectives", "B2", "adjective", null, true],
    [800, "Stringent", "Estricto / Riguroso", "adjectives", "B2", "adjective", null, true],
    [801, "Exemplary", "Ejemplar", "adjectives", "B2", "adjective", null, true],
    // --- Tema 9: Verbos de Acción Complejos & Trabajo (ADV-VE) ---
    [802, "Confirm", "Confirmar", "verbs", "B1", "verb", null, true],
    [803, "Cancel", "Cancelar", "verbs", "B1", "verb", null, true],
    [804, "Update", "Actualizar", "verbs", "B1", "verb", null, true],
    [805, "Receive", "Recibir", "verbs", "B1", "verb", null, true],
    [806, "Request", "Solicitar", "verbs", "B1", "verb", null, true],
    [807, "Improve", "Mejorar", "verbs", "B1", "verb", null, true],
    [808, "Increase", "Aumentar", "verbs", "B1", "verb", null, true],
    [809, "Decrease", "Disminuir", "verbs", "B1", "verb", null, true],
    [810, "Develop", "Desarrollar", "verbs", "B1", "verb", null, true],
    [811, "Manage", "Gestionar / Dirigir", "verbs", "B1", "verb", null, true],
    [812, "Negotiate", "Negociar", "verbs", "B1", "verb", null, true],
    [813, "Convince", "Convencer", "verbs", "B1", "verb", null, true],
    [814, "Achieve", "Lograr / Alcanzar", "verbs", "B1", "verb", null, true],
    [815, "Avoid", "Evitar", "verbs", "B1", "verb", null, true],
    [816, "Resolve", "Resolver", "verbs", "B1", "verb", null, true],
    [817, "Suggest", "Sugerir", "verbs", "B1", "verb", null, true],
    [818, "Recommend", "Recomendar", "verbs", "B1", "verb", null, true],
    [819, "Require", "Requerir", "verbs", "B1", "verb", null, true],
    [820, "Allow", "Permitir", "verbs", "B1", "verb", null, true],
    [821, "Prevent", "Prevenir / Evitar", "verbs", "B1", "verb", null, true],
    [822, "Analyze", "Analizar", "verbs", "B1", "verb", null, true],
    [823, "Compare", "Comparar", "verbs", "B1", "verb", null, true],
    [824, "Evaluate", "Evaluar", "verbs", "B1", "verb", null, true],
    [825, "Identify", "Identificar", "verbs", "B1", "verb", null, true],
    [826, "Measure", "Medir", "verbs", "B1", "verb", null, true],
    [827, "Implement", "Implementar", "verbs", "B2", "verb", null, true],
    [828, "Optimize", "Optimizar", "verbs", "B2", "verb", null, true],
    [829, "Streamline", "Optimizar / Agilizar", "verbs", "B2", "verb", null, true],
    [830, "Prioritize", "Priorizar", "verbs", "B2", "verb", null, true],
    [831, "Delegate", "Delegar", "verbs", "B2", "verb", null, true],
    [832, "Facilitate", "Facilitar", "verbs", "B2", "verb", null, true],
    [833, "Execute", "Ejecutar", "verbs", "B2", "verb", null, true],
    [834, "Consolidate", "Consolidar", "verbs", "B2", "verb", null, true],
    [835, "Formulate", "Formular", "verbs", "B2", "verb", null, true],
    [836, "Integrate", "Integrar", "verbs", "B2", "verb", null, true],
    [837, "Mitigate", "Mitigar", "verbs", "B2", "verb", null, true],
    [838, "Leverage", "Aprovechar / Apalancar", "verbs", "B2", "verb", null, true],
    [839, "Synthesize", "Sintetizar", "verbs", "B2", "verb", null, true],
    [840, "Sustain", "Sostener / Mantener", "verbs", "B2", "verb", null, true],
    [841, "Validate", "Validar", "verbs", "B2", "verb", null, true],
    [842, "Speculate", "Especular", "verbs", "B2", "verb", null, true],
    [843, "Diversify", "Diversificar", "verbs", "B2", "verb", null, true],
    [844, "Empower", "Empoderar / Capacitar", "verbs", "B2", "verb", null, true],
    [845, "Acknowledge", "Reconocer / Admitir", "verbs", "B2", "verb", null, true],
    [846, "Authorize", "Autorizar", "verbs", "B2", "verb", null, true],
    [847, "Substantiate", "Fundamentar / Justificar", "verbs", "B2", "verb", null, true],
    [848, "Pioneer", "Pionero / Ser pionero", "verbs", "B2", "verb", null, true],
    [849, "Overhaul", "Revisar a fondo / Remodelar", "verbs", "B2", "verb", null, true],
    [850, "Standardize", "Estandarizar", "verbs", "B2", "verb", null, true],
    [851, "Reconcile", "Reconciliar / Conciliar", "verbs", "B2", "verb", null, true],
    [852, "Instigate", "Instigar / Promover", "verbs", "B2", "verb", null, true],

    // --- Tema 10: Conectores Lógicos & Discurso Avanzado (CON) [EXPRESIONES SIN IMAGEN] ---
    [853, "Furthermore", "Además / Asimismo", "expressions", "B2", "expression", null, false],
    [854, "However", "Sin embargo", "expressions", "B2", "expression", null, false],
    [855, "Therefore", "Por lo tanto", "expressions", "B2", "expression", null, false],
    [856, "Meanwhile", "Mientras tanto", "expressions", "B2", "expression", null, false],
    [857, "Although", "Aunque", "expressions", "B2", "expression", null, false],
    [858, "Consequently", "Por consiguiente", "expressions", "B2", "expression", null, false],
    [859, "Nevertheless", "No obstante", "expressions", "B2", "expression", null, false],
    [860, "Otherwise", "De lo contrario", "expressions", "B2", "expression", null, false],
    [861, "In addition", "Además", "expressions", "B2", "expression", null, false],
    [862, "Despite", "A pesar de", "expressions", "B2", "expression", null, false],
    [863, "Instead of", "En lugar de", "expressions", "B2", "expression", null, false],
    [864, "According to", "Según / De acuerdo con", "expressions", "B2", "expression", null, false],
    [865, "In order to", "Para / Con el fin de", "expressions", "B2", "expression", null, false],
    [866, "Due to", "Debido a", "expressions", "B2", "expression", null, false],
    [867, "As a result", "Como resultado", "expressions", "B2", "expression", null, false],
    [868, "In light of", "A la luz de / Teniendo en cuenta", "expressions", "B2", "expression", null, false],
    [869, "Given that", "Dado que", "expressions", "B2", "expression", null, false],
    [870, "Provided that", "Siempre que / Con tal de que", "expressions", "B2", "expression", null, false],
    [871, "With regard to", "Con respecto a", "expressions", "B2", "expression", null, false],
    [872, "In spite of", "A pesar de", "expressions", "B2", "expression", null, false],
    [873, "To sum up", "En resumen / Para resumir", "expressions", "B2", "expression", null, false],
    [874, "In contrast", "En contraste", "expressions", "B2", "expression", null, false],
    [875, "On the contrary", "Al contrario", "expressions", "B2", "expression", null, false],
    [876, "For instance", "Por ejemplo", "expressions", "B2", "expression", null, false],
    [877, "Namely", "A saber / Es decir", "expressions", "B2", "expression", null, false],
    [878, "To put it another way", "Dicho de otra manera", "expressions", "B2", "expression", null, false],
    [879, "In essence", "En esencia", "expressions", "B2", "expression", null, false],
    [880, "At first glance", "A primera vista", "expressions", "B2", "expression", null, false],
    [881, "Under these circumstances", "Bajo estas circunstancias", "expressions", "B2", "expression", null, false],
    [882, "All in all", "En general / En definitiva", "expressions", "B2", "expression", null, false],
    [883, "Be that as it may", "Sea como fuere", "expressions", "B2", "expression", null, false],
    [884, "For the most part", "En su mayor parte", "expressions", "B2", "expression", null, false],
    [885, "To a certain extent", "Hasta cierto punto", "expressions", "B2", "expression", null, false],
    [886, "In all likelihood", "Con toda probabilidad", "expressions", "B2", "expression", null, false],
    [887, "On the face of it", "A primera vista / A juzgar por las apariencias", "expressions", "B2", "expression", null, false],
    [888, "Notwithstanding", "A pesar de / No obstante", "expressions", "B2", "expression", null, false],
    [889, "In light of this", "En vista de esto", "expressions", "B2", "expression", null, false],
    [890, "Suffice it to say", "Basta decir que", "expressions", "B2", "expression", null, false],
    [891, "To put it simply", "En pocas palabras", "expressions", "B2", "expression", null, false],
    [892, "Without a doubt", "Sin lugar a dudas", "expressions", "B2", "expression", null, false],
    [893, "In retrospect", "En retrospectiva", "expressions", "B2", "expression", null, false],
    [894, "In tandem with", "En conjunto con", "expressions", "B2", "expression", null, false],
    [895, "For all intents and purposes", "A todos los efectos prácticos", "expressions", "B2", "expression", null, false],
    [896, "Broadly speaking", "En términos generales", "expressions", "B2", "expression", null, false],
    [897, "Case in point", "Un buen ejemplo de ello", "expressions", "B2", "expression", null, false],
    [898, "By and large", "En general / Por lo general", "expressions", "B2", "expression", null, false],
    [899, "To state the obvious", "Para decir lo obvio", "expressions", "B2", "expression", null, false],
    [900, "As far as I'm concerned", "En lo que a mí respecta", "expressions", "B2", "expression", null, false],
    [901, "It stands to reason", "Es lógico / Es natural pensar que", "expressions", "B2", "expression", null, false],
    [902, "All things considered", "Teniendo todo en cuenta", "expressions", "B2", "expression", null, false]
];

// GENERADOR AUTOMÁTICO DE URLs (Convierte espacios a minúsculas con guion; asigna null si hasImage es false)
export const VOCABULARY_DATABASE = RAW_VOCABULARIO.map(([id, word, spanish, category, level, syntax, article, hasImage]) => {
    let mediaUrl = null;

    if (hasImage) {
        const cleanFileName = word
            .toLowerCase()
            .replace(/'/g, '')
            .trim()
            .replace(/\s+/g, '-');

        mediaUrl = `${SUPABASE_BASE_URL}/${category}/${cleanFileName}.svg`;
    }

    return {
        id,
        word,
        spanish,
        category,
        level,
        syntax,
        article,
        media_url: mediaUrl
    };
});

// Métodos de consulta directos O(1)
export function getWordById(id) {
    return VOCABULARY_DATABASE.find(item => item.id === id) || null;
}

export function getWordsByCategory(categoryName) {
    return VOCABULARY_DATABASE.filter(item => item.category === categoryName);
}

export function getWordsByLevel(levelCode) {
    return VOCABULARY_DATABASE.filter(item => item.level === levelCode);
}